
     
	 <img src="/images/MeStreetWalk.jpg" alt="" class="centercolumn" style="width:60%;" >

	 <div class="caption">
	 This was taken just outside my apartment in New York.  
         I spend my time between Manhattan and Geneva, Switzerland.
	 </div>

	 <br>
	 
	 <img src="/images/Profile.jpg" alt="" class="centercolumn"  style="width:80%;" >

	 <div class="caption">
	  Please refrain from spamming me.  
	  Though, if you're an automatic spam bot, you probably won't heed this plea.
	 </div>
