


	 <p style="text-align:center">
	 <br>	 
	  <b>Welcome to Spontaneous Symmetry:</b> 
	  <br>
	  <i>A site devoted to Physics, Math, Computing, and Life.</i>
	 </p>

	 <p>
	 This is my personal website, a place where I can share a bit about who I am and what I do. 
	 I'm a scientist, full time student, and part time programmer.
	 Feel	free to browse this site, free of charge.  
	 My hope is that you'll learn something about the world around you, and possibly about the site's author.
	 Thank you very much for stopping by.
	 </p>
	 
	 <br>

	 <p>
	 So, why the name <i>Spontaneous Symmetry</i>?  
	 The term comes from a phenomenon that appears in may fields of physics known as <i>spontaneous symmetry breaking.</i>
	 Symmetries are all around us and shape our lives in ways few understand.  
	 On an aesthetic level, symmetries are considered beautiful and visually pleasing.
	 But the mathematical concept of a symmetry is much deeper than the familiar definition.
	 On a fundamental level, symmetries govern how the world works.
	 They are the language of the most fundamental physical processes that we can describe.
	 </p>

	 <img src="/images/symmetry_e8.jpg" alt=""  border="0" >

	 <div class="caption">
	 <p>	 
	  A mathematical group known as E8.  
	  It is the largest <Q>exceptional</Q> lie group, 
	  an algebraic structure known for its many beautiful symmetries.
	 </p>
	 </div>
    
