


	 <img src="/images/higgs-boson.jpg" alt="" class="centercolumn" >

	 <div class="caption" >
	 A simulated image of a potential collision event causing the creation and almost immediate decay of a Higgs Boson.
	 </div>
     
        <p>&nbsp;</p>
	 
	 <img src="/images/atlas-detector.jpg" alt="" class="centercolumn"   >

	 <div class="caption" >
	  A picture of the ATLAS detector as it was being constructed.  
	  The eight large structures are toroidal magnets which create a magnetic field as a part of the muon system.
	 </div>

        <p>&nbsp;</p>

	 <img src="/images/standardmodellagrangian.gif" alt="" class="centercolumn" >

	 <div class="caption">
	 The standard model lagrangian: the equation that describes our current model for fundamental physics.  
	 Gravity is not included.
	 </div>




	 <div class="bar">
	 <p>&nbsp;</p>
	 </div>

