


<br>
<center><b>CODE</b></center>
<br>


Here is a central place to access the code on this site.

Please select a program below: <br>

<br>

<a href="Quadratic"> Quadratic <br> </a>
<a href="BouncingBalls"> Bouncingballs <br> </a>

<!--

<form name="myform" action="#code" method="POST">
  <div align="center">
    <select name="CodeToRun">
      <option value="GetLinksFromReader">GetLinksFromReader</option>
      <option value="RocksPaper">RocksPaper</option>
    </select>
    <INPUT TYPE=SUBMIT VALUE="Go">
  </div>
</form>
-->

<a href="#code"></a>

<!--
<?php   

   /* Get the Variable */

   if( count( $_POST ) != 0 ) {
   
   $CodeToRun = $_POST['CodeToRun'];
   
   if($CodeToRun == 'GetLinksFromReader') {
   echo '<pre class="prettyprint" id="python">';
   include "src/GetLinksFromReader.py";
   echo '</pre>';
   }

   else if($CodeToRun == 'RocksPaper') {
   echo '<pre class="prettyprint" id="python">';
   include "src/RocksPaper.py";
   echo '</pre>';
   }

}

   ?>  



-->
