
<body onload="prettyPrint()" >

  <!-- Add the Common Header: -->
  <?php include $HOME_DIR_REL . "../tools/header.inc"; ?>

  <!-- Add the midsection of the body -->
  <?php include $HOME_DIR_REL . "../tools/midsection_1column.inc"; ?>

  <!-- Add the footer: -->
  <?php include $HOME_DIR_REL . "../tools/footer.inc"; ?>

  <!-- Add analytics: -->
  <?php include $HOME_DIR_REL . "../analytics/ga.inc"; ?>

</body>
