
<head>

  <title>Bouncing Balls</title>

  <?php include $HOME_DIR_REL . "../tools/commonhead.inc";  ?>
  <script type="text/javascript" src="<?php echo $HOME_DIR_REL ?>jquery/jquery.js"></script>
  <script type="text/javascript" src="<?php echo $HOME_DIR_REL ?>jquery/functions/CodeVisualization.js"></script>
  <script type="text/javascript" src="draw.js"></script>
  
  <!-- Include google's "code prettify" functions: -->
  <link href="<?php echo $HOME_DIR_REL ?>google-code-prettify/prettify.css" type="text/css" rel="stylesheet" >
  <script type="text/javascript" src="<?php echo $HOME_DIR_REL ?>google-code-prettify/prettify.js"></script>



</head>
