
<br>
<center><b>Bouncing Balls</b></center>
<br>

<center>

A simple javascript program to demonstrate some <br>
animation and some (very simple) physics.

<br>
<br>


<canvas id="canvas" width="500" height="500" style="border:1px solid blue; margin: 0px auto;"> </canvas> 

    <br> <button type="button" id="stopButton" OnClick="stoploop()"> Start/Stop </button>

<br>
<br>


<button id="showcodebutton">Show/Hide Code</button>

</center>
<div id="showcode"> 

  <?php   
     echo '<pre class="prettyprint" id="python">';
     include "draw.js";
     echo '</pre>';
     ?>  

</div>




<br>
<br>
