
<head>

  <title>Logistic Map</title>

  <?php include $HOME_DIR . "../tools/commonhead.inc";  ?>
  <script type="text/javascript" src="<?php echo $HOME_DIR ?>jquery/jquery.js"></script>

  <!-- Include google's "code prettify" functions: -->
  <script type="text/javascript" src="<?php echo $HOME_DIR ?>jquery/functions/CodeVisualization.js"></script>  
  <link href="/google-code-prettify/prettify.css" type="text/css" rel="stylesheet" >
  <script type="text/javascript" src="/google-code-prettify/prettify.js"></script>



</head>
