
<br>
<center><b>Logistic</b></center>
<br>

<center>

A simple java applet which demonstrates <br>
the chaos in the Logistic Map.<br>
(This requires you to enable Java )

<br>
<br>

<APPLET CODE=Logistic.class WIDTH=600 HEIGHT=300>
  <param name="text" value="Hello">     
</APPLET>


<br>
<br>


<button id="showcodebutton">Show/Hide Code</button>

</center>

<div id="showcode"> 

  <?php   
     echo '<pre class="prettyprint" id="java">';
     include "Logistic.java";
     echo '</pre>';
     ?>  

</div>
