
<head>
  
  <title>Rocks Paper</title>

  <?php include $HOME_DIR . "../tools/commonhead.inc";  ?>
  
  <script type="text/javascript" src="<?php echo $HOME_DIR ?>jquery/jquery.js"></script>

  <script type="text/javascript" src="game.js"></script>  

  <script type="text/javascript" src="<?php echo $HOME_DIR ?>jquery/jquery.validate.min.js"></script>
<!--  <script type="text/javascript" src="FormValidate.js"></script>  -->

  <!-- Include google's "code prettify" functions: -->
  <script type="text/javascript" src="<?php echo $HOME_DIR ?>jquery/functions/CodeVisualization.js"></script>
  <link href="/google-code-prettify/prettify.css" type="text/css" rel="stylesheet" >
  <script type="text/javascript" src="/google-code-prettify/prettify.js"></script>

  

</head>
