#!/bin/bash

echo "Pushing to production server"

while read oldrev newrev ref
do
    branch=`echo $ref | cut -d/ -f3`
    if [ "production" == "$branch" -o "master" == "$branch" ]; then

        SITE_DIRECTORY=/var/www/spontaneoussymmetry

        echo 'Pushing changes to Amazon EC2 Production'
        sudo git --work-tree=$SITE_DIRECTORY checkout -f $branch

        echo 'Updating python dependencies'
        cd $SITE_DIRECTORY && . venv/bin/activate && pip install -r requirements.txt && deactivate && cd -

        echo 'Restarting uwsgi service'
        sudo service uwsgi restart

        echo 'Current uwsgi status:'
        service uwsgi status

        echo 'Current nginx status:'
        service nginx status

    else

        echo "Attempting to push to a branch that isn't master: $branch"
        echo "Bailing out"
        exit 1

    fi

done
