

	<br>
	<center><b>WORK</b></center>

	 <p>
	   I am a graduate student working as a member of the ATLAS experiment.  
	   My specific interests include Top quark physics, the Missing Energy Trigger, Physics Analysis Tools, and Statistics.

	 </p> 

	 <p>
	 ATLAS is an all-purpose particle detector whose primary goal is the discovery of new particles.
	 However, before it can claim new discoveries, it must understand standard physics well enough to distinguish non-standard physics.
	 A particle physicist would say that you first have to understand your background before you can find your signal.
	 A very important background comes from the production of Top Quarks.
	 Though the Top was initially discovered in 1995, it is extremely important to understand how often tops are made by the LHC and what it looks like when they are produced.
	 Top quark events can look similar to, for example, Higgs Boson events, so understanding Top physics is a crucial preliminary step to finding the Higgs boson, as well as many other interesting physical processes.
	 </p> 

	 <p>
	 But before one can analyze data and search for new particles, one must collect data.
	 LHC smashes protons together at a rate of about 4 million per second.
	 Each event that the ATLAS detector records takes up between 1 and 2 MB of data.
	 If ATLAS were to record every collision, it would be storing about 5 Terabytes per second.
	 For many reasons, this rate is far from sustainable.
	 Hence, ATLAS uses a system of hardware and software called the trigger to first determine if a particular collision is interesting before saving it.
	 I work on one aspect of the trigger that looks for what is called Missing Energy to determine if an event should be kept or discarded.
	 </p> 
    
	 <p>
	 After a theory has been made and data has been collected, one must have the proper tools in order to properly and efficiently analyze data and come to significant conclusions.
	 This is often the most difficult and most important part of Particle Physics.
	 I am interested in developing and maintaining these software tools that are used to interpret, visualize, and understand statistically the particle collisions at ATLAS.
	 Members of the ATLAS experiment use several software packages and frameworks to do analysis, all of which is open and most of which is developed by members of the experiment 
	 (see the <a href="/links">LINKS</a> section for examples).
	 </p> 
    
	 <p>
	 A graduate student in High Energy Experimental Physics plays many roles.
	 As a member of ATLAS, one must understand the underlying physics and the hardware of our accelerator, the LHC.
	 One must know about protons, how they are composed of quarks, and how these quarks interact when protons are collided.
	 One must understand fundamental particle physics and what final states emerge after collisions, how likely these states are to occur, and what they look like.
	 One must understand the physics of particle detectors, how different particles interact with these detectors, and how one can use the readout of these detectors to reconstruct escaping particles.
	 One must be able to work with large data sets, to move and organize this data, to process and visualize it, and to find patterns and meaning among a huge amount of information.
	 And finally, one must be able to do formal statistical analysis of this data, to claim discovery or reject hypothesis, and to relate statistical observations back to fundamental theories.
	 </p> 
