

	 <img src="/images/topquarkevent.jpg" alt="" class="centercolumn"  >

	 <div class="caption">	 
	 An example of a proton-proton event that leads to the production of two top quarks (specifically, one top and one anti-top).
	 The top quarks quickly decay into jets, muons, electrons, and neutrinos.
	 </div>

	 <br>

	 <img src="/images/AtlasEvent.jpg" alt="" class="centercolumn"  >

	 <div class="caption">	 
	 An example of a collision event as seen by the ATLAS detector.
	 Several example particles are show interacting with the ATLAS.
	 </div>


	 <img src="/images/DijetResonance.jpg" alt="" class="centercolumn"  >

	 <div class="caption">	 
	 A public result from ATLAS on the invariant mass of jets.
	 From: <a href="http://arxiv.org/abs/1008.2461">arXiv:1008.2461</a>
	 </div>

	 <br>
	 <br>
