


     <?php include "/home/spontane/tools/header.inc"; ?>

     <div class="midsection">
     
        <div class="leftcol">

	 &nbsp;	
	
        </div>
     
        <div class="midcol">

	 <?php include "./midcolumn.inc"; ?>

        </div>

        <div class="rightcol">
     
         <?php include "./rightcolumn.inc"; ?>

        </div> 

	 <div class="bar">
	 
	  <p>&nbsp;</p>
	 
	 </div>

     </div>

     <?php include "/home/spontane/tools/footer.inc"; ?>
     <?php include ("/home/spontane/analytics/ga.inc"); ?>
