

<meta name="keywords" content="spontaneous symmetry, spontaneoussymmetry, george lewis, Higgs, ATLAS, CERN, Statistics, physics, quark" >

<link rel="shortcut icon" href="/favicon.ico" >

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >


<!-- Include the stylesheet: -->
<link rel="stylesheet" href="<?php echo $HOME_DIR ?>styles/style.css" type="text/css" media="screen">

<!-- Include google's "code prettify" functions: -->
<link href="/google-code-prettify/prettify.css" type="text/css" rel="stylesheet" >
<script type="text/javascript" src="/google-code-prettify/prettify.js"></script>
