
<?php if( file_exists("title.inc") ) { include "title.inc"; } ?>

<meta name="keywords" content="spontaneous symmetry, spontaneoussymmetry, george lewis, Higgs, ATLAS, CERN, Statistics, physics, quark" >

<link rel="shortcut icon" href="/favicon.ico" >

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

<!-- Include the stylesheet: -->
<link rel="stylesheet" href="<?php echo $HOME_DIR ?>styles/style.css" type="text/css" media="screen">
