


	<br>
	<center><b>LINKS</b></center>

	<br>
	
	<b>Software for High Energy Physics:</b>
	 <ul>

	 <li> <a href="http://root.cern.ch/drupal/">ROOT</a>: A software package used to store data and make plots </li>
	 <li> <a href="https://twiki.cern.ch/twiki/bin/viewauth/Atlas/AthenaFramework">Athena</a>: The control framework used to run real-time detector data collection and offline analysis. </li>
	 <li> <a href="https://twiki.cern.ch/twiki/bin/viewauth/Atlas/PanDA">PanDA</a>: A tool used to perform distributed analysis so one can run jobs using computers all around the world</li>
	 <li> <a href="http://sourceforge.net/apps/mediawiki/sframe/index.php?title=Main_Page">SFrame</a>: A package used for the parallel processing of Particle Physics data structures
	 <li> <a href="http://roofit.sourceforge.net/">RooFit</a>: A statistical package used to build models, run regressions, perform likelihood minimizations, and to implement many other forms of statistical analysis 
	 <li> <a href="https://twiki.cern.ch/twiki/bin/view/RooStats/WebHome">RooStats</a>: A set of classes built on top of RooFit to perform advanced statistical tests


	 </ul>


	 <b>Blogs and comics:</b>

	 <ul>

	 <li> <a href="http://blogs.discovermagazine.com/cosmicvariance/">Cosmic Variance</a>: A blog by physicist Sean Carroll </li>
	 <li> <a href="http://flowingdata.com/">Flowing Data</a>: A site devoted to data visualization </li>
	 <li> <a href="http://www.cepr.net/index.php/beat-the-press/">Beat the Press</a>: A financial blog about the media </li>
	 <li> <a href="http://www.xkcd.com/">xkcd</a>: A web comic about science... sometimes </li>
	 <li> <a href="http://www.qwantz.com/index.php">Dinosaur Comics</a>: A web comic about dinosaurs and philosophy </li>
	 <li> <a href="http://blog.moviefone.com/bloggers/david-ehrlich/">David Ehrlich</a> @ Cinematical: A high-brow film blog with low-brow humor </li>
	 <li> <a href="http://rationallyspeaking.blogspot.com/">Rationally Speaking</a>: A philosophy blog with lots of interesting links </li>
	 <li> <a href="http://resonaances.blogspot.com/">Resonaances</a>: A blog on high energy physics

	 </ul>
