


<br>
<center><b>LINKS</b></center>

<br>


<b>Science Blogs:</b>
<ul>


  <li> <a href="http://blogs.discovermagazine.com/cosmicvariance">Cosmic Variance</a>  </li>
  <li> <a href="http://resonaances.blogspot.com/">RÉSONAANCES</a>  </li>
  <li> <a href="http://www.science20.com/quantum_diaries_survivor">dorigo's blog</a>  </li>
  <li> <a href="http://www.math.columbia.edu/~woit/wordpress">Not Even Wrong</a>  </li>
  <li> <a href="http://www.quantumdiaries.org">Quantum Diaries</a>  </li>
  <li> <a href="http://blogs.plos.org/badphysics">The Language of Bad Physics</a>  </li>
  <li> <a href="http://www.skepticalscience.com/">Skeptical Science</a>  </li>



</ul>



<b>Software for High Energy Physics:</b>
<ul>

  <li> <a href="http://root.cern.ch/drupal/">ROOT</a>: A software package used to store data and make plots </li>
  <li> <a href="https://twiki.cern.ch/twiki/bin/viewauth/Atlas/AthenaFramework">Athena</a>: The control framework used to run real-time detector data collection and offline analysis. </li>
  <li> <a href="https://twiki.cern.ch/twiki/bin/viewauth/Atlas/PanDA">PanDA</a>: A tool used to perform distributed analysis so one can run jobs using computers all around the world</li>
  <li> <a href="http://sourceforge.net/apps/mediawiki/sframe/index.php?title=Main_Page">SFrame</a>: A package used for the parallel processing of Particle Physics data structures
  <li> <a href="http://roofit.sourceforge.net/">RooFit</a>: A statistical package used to build models, run regressions, perform likelihood minimizations, and to implement many other forms of statistical analysis 
  <li> <a href="https://twiki.cern.ch/twiki/bin/view/RooStats/WebHome">RooStats</a>: A set of classes built on top of RooFit to perform advanced statistical tests


</ul>


<b>Blogs and comics:</b>

<ul>

  <li> <a href="http://blogs.discovermagazine.com/cosmicvariance/">Cosmic Variance</a>: A blog by physicist Sean Carroll </li>
  <li> <a href="http://flowingdata.com/">Flowing Data</a>: A site devoted to data visualization </li>
  <li> <a href="http://www.cepr.net/index.php/beat-the-press/">Beat the Press</a>: A financial blog about the media </li>
  <li> <a href="http://www.xkcd.com/">xkcd</a>: A web comic about science... sometimes </li>
  <li> <a href="http://www.qwantz.com/index.php">Dinosaur Comics</a>: A web comic about dinosaurs and philosophy </li>
  <li> <a href="http://blog.moviefone.com/bloggers/david-ehrlich/">David Ehrlich</a> @ Cinematical: A high-brow film blog with low-brow humor </li>
  <li> <a href="http://rationallyspeaking.blogspot.com/">Rationally Speaking</a>: A philosophy blog with lots of interesting links </li>
  <li> <a href="http://resonaances.blogspot.com/">Resonaances</a>: A blog on high energy physics

</ul>


<b> Others: </b>


<li> <a href="http://arxiv.org/">hep-ex updates on arXiv.org</a>  </li>
<li> <a href="http://arxiv.org/">hep-ph updates on arXiv.org</a>  </li>
<li> <a href="http://niemann.blogs.nytimes.com/">Abstract City</a>  </li>
<li> <a href="http://bourgeoiseldorado.tumblr.com/">Bourgeois Eldorado</a>  </li>
<li> <a href="http://www.buzzmachine.com">BuzzMachine</a>  </li>
<li> <a href="http://www.radiohead.com/deadairspace/">dead air space</a>  </li>
<li> <a href="http://www.denizenmag.com">Denizen</a>  </li>
<li> <a href="http://www.qwantz.com">Dinosaur Comics</a>  </li>
<li> <a href="http://www.drinkhacker.com">Drinkhacker.com</a>  </li>
<li> <a href="http://evgrieve.com/">EV Grieve</a>  </li>
<li> <a href="http://www.patheos.com/blogs/friendlyatheist">Friendly Atheist</a>  </li>
<li> <a href="http://www.grantland.com">Grantland: Home Page</a>  </li>
<li> <a href="http://hyperboleandahalf.blogspot.com/">Hyperbole and a Half</a>  </li>
<li> <a href="http://nakedsecurity.sophos.com">Naked Security - Sophos</a>  </li>
<li> <a href="http://www.phdcomics.com">PHD Comics</a>  </li>
<li> <a href="http://www.ateaseweb.com">Radiohead At Ease</a>  </li>
<li> <a href="http://rationallyspeaking.blogspot.com/">Rationally Speaking</a>  </li>
<li> <a href="http://www.slate.com?from=rss">Slate Magazine</a>  </li>
<li> <a href="http://www.pbfcomics.com/">The Perry Bible Fellowship</a>  </li>
<li> <a href="http://xkcd.com/">xkcd.com</a>  </li>
<li> <a href="http://zooeydeschanel.tumblr.com/">ZOOEY'S MISCELLANY</a>  </li>
<li> <a href="http://adamkatz.tumblr.com/">Adam Katz</a>  </li>
<li> <a href="http://www.calculatedriskblog.com/">Calculated Risk</a>  </li>
<li> <a href="http://daringfireball.net/">Daring Fireball</a>  </li>
<li> <a href="http://derivativedribble.wordpress.com">Derivative Dribble</a>  </li>
<li> <a href="http://allthingsd.com">Digital Daily</a>  </li>
<li> <a href="http://www.digitalurban.org/">Digital Urban</a>  </li>
<li> <a href="http://www.engadget.com">Engadget</a>  </li>
<li> <a href="http://ftalphaville.ft.com/blog">FT Alphaville</a>  </li>
<li> <a href="http://kottke.org/">kottke.org</a>  </li>
<li> <a href="http://www.bloomberg.com/blogs/paul-kedrosky/">Paul Kedrosky - Bloomberg</a>  </li>
<li> <a href="http://rick.bookstaber.com/">Rick Bookstaber</a>  </li>
<li> <a href="http://seekingalpha.com/tag/editors-picks">Seeking Alpha Editors' Picks stocks</a>  </li>
<li> <a href="http://www.technologyreview.com/">Technology Review RSS Feeds</a>  </li>
<li> <a href="http://www.cepr.net/">Beat the Press</a>  </li>
<li> <a href="http://fivethirtyeight.blogs.nytimes.com/">FiveThirtyEight</a>  </li>
<li> <a href="http://www.frumforum.com">FrumForum » News</a>  </li>
<li> <a href="http://kristof.blogs.nytimes.com/">Nicholas D. Kristof</a>  </li>
<li> <a href="http://topics.nytimes.com/top/opinion/editorialsandoped/oped/columnists/index.html?">NYT > Columnists</a>  </li>
<li> <a href="http://topics.nytimes.com/top/opinion/editorialsandoped/editorials/index.html?">NYT > Editorials</a>  </li>
<li> <a href="http://krugman.blogs.nytimes.com/">Paul Krugman</a>  </li>
<li> <a href="http://politicalirony.com">Political Irony</a>  </li>
<li> <a href="http://www.tnr.com/blogs/Jonathan-Chait">The New Republic - Jonathan Chait Feed</a>  </li>
<li> <a href="http://thinkprogress.org">Wonk Room</a>  </li>
<li> <a href="http://robin-eggblue.blogspot.com/">all my pretty hates</a>  </li>
<li> <a href="http://allthingsfangirl.blogspot.com/">All Things Fangirl</a>  </li>
<li> <a href="http://www.cinemablend.com/kinokatey/">Cinema Blend's Kino Katey</a>  </li>
<li> <a href="http://criterioncorner.tumblr.com/">Criterion Corner</a>  </li>
<li> <a href="http://hoggteaching.blogspot.com/">Hogg's Teaching</a>  </li>
<li> <a href="http://jengoestocollege.blogspot.com/">jen goes to college</a>  </li>
<li> <a href="http://mermaidchronicles.wordpress.com">Mermaid Chronicles</a>  </li>
<li> <a href="http://readitordont.tumblr.com/">My Inconvenient Life</a>  </li>
<li> <a href="http://mattpatches.com">Patchlog</a>  </li>
<li> <a href="http://raabtastic.blogspot.com/">Physics in the Time of Diarrhea</a>  </li>
<li> <a href="http://ramblesonrye.blogspot.com/">Rambles on Rye</a>  </li>
<li> <a href="http://sagansbrain.blogspot.com/">Sagan's Brain</a>  </li>
<li> <a href="http://shorteasywordsreviews.blogspot.com/">Short, Easy Words Like &quot;What About Lunch?&quot;</a>  </li>
<li> <a href="http://www.spontaneoussymmetry.com/blog">SpontaneousSymmetry</a>  </li>
<li> <a href="http://thedanifesto.blogspot.com/">The Danifesto</a>  </li>
<li> <a href="http://theecstatictruth.tumblr.com/">the ecstatic truth</a>  </li>
<li> <a href="http://blog.moviefone.com">The Moviefone Blog</a>  </li>
<li> <a href="http://thesophisticates.tumblr.com/">The Sophisticates</a>  </li>
<li> <a href="http://theytoldmetofindrichhusband.com">They Told Me to Find a Rich Husband</a>  </li>
<li> <a href="http://www.thisisthegreenroom.com">This is the Green Room</a>  </li>
<li> <a href="http://worksofgonzales.posterous.com">What I Made Instead Of Money</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=cougarman8">Uploads by cougarman8</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=dcullen617">Uploads by dcullen617</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=FreakFolk391">Uploads by FreakFolk391</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=GirlCrisis">Uploads by GirlCrisis</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=mreebee3">Uploads by mreebee3</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=mynameiskate3">Uploads by mynameiskate3</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=PomplamooseMusic">Uploads by PomplamooseMusic</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=SugarisAnnoyed">Uploads by SugarisAnnoyed</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=thricedotted">Uploads by thricedotted</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=troubleclef">Uploads by troubleclef</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=ValenceBand">Uploads by ValenceBand</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=warrenmusic">Uploads by warrenmusic</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=WatchKateWatching">Uploads by WatchKateWatching</a>  </li>
<li> <a href="http://www.youtube.com/profile_videos?user=whitehouse">Uploads by whitehouse</a>  </li>

<li> <a href="http://blogs.discovermagazine.com/80beats">80beats</a>  </li>
<li> <a href="http://pdg2.lbl.gov/atlasblog">ATLAS Control Room Blog</a>  </li>
<li> <a href="http://blogs.discovermagazine.com/badastronomy">Bad Astronomy</a>  </li>
<li> <a href="http://www.beyond-physics.org">Beyond Physics</a>  </li>
<li> <a href="http://scienceblogs.com/brookhaven/">Brookhaven Bits &amp; Bytes</a>  </li>
<li> <a href="http://thinkprogress.org">Climate Progress</a>  </li>
<li> <a href="http://twistedphysics.typepad.com/cocktail_party_physics/">Cocktail Party Physics</a>  </li>
<li> <a href="http://blogs.discovermagazine.com/cosmicvariance">Cosmic Variance</a>  </li>
<li> <a href="http://blog.energy.gov">DOE Blog</a>  </li>
<li> <a href="http://www.science20.com/quantum_diaries_survivor">dorigo's blog</a>  </li>
<li> <a href="http://blogs.reuters.com/emanuelderman">Emanuel Derman</a>  </li>
<li> <a href="http://hoggresearch.blogspot.com/">Hogg's Research</a>  </li>
<li> <a href="http://gordonwatts.wordpress.com">Life as a Physicist</a>  </li>
<li> <a href="http://stuver.blogspot.com/">Living LIGO</a>  </li>
<li> <a href="http://experimentalmath.info/blog">Math Drudge</a>  </li>
<li> <a href="http://mathbabe.org">mathbabe</a>  </li>
<li> <a href="http://theness.com/neurologicablog">NeuroLogica Blog</a>  </li>
<li> <a href="http://www.math.columbia.edu/~woit/wordpress">Not Even Wrong</a>  </li>
<li> <a href="http://www.nytimes.com/pages/science/index.html?partner=rss&amp;emc=rss">NYT > Science</a>  </li>
<li> <a href="http://ompp.wordpress.com">Occasional Musings of a Particle Physicist</a>  </li>
<li> <a href="http://profmattstrassler.com">Of Particular Significance</a>  </li>
<li> <a href="http://physicsbuzz.physicscentral.com/">Physics Buzz</a>  </li>
<li> <a href="http://physicsformom.blogspot.com/">Physics for my Mom</a>  </li>
<li> <a href="http://www.quantumdiaries.org">Quantum Diaries</a>  </li>
<li> <a href="http://richardwiseman.wordpress.com">Richard Wiseman's Blog</a>  </li>
<li> <a href="http://resonaances.blogspot.com/">RÉSONAANCES</a>  </li>
<li> <a href="http://www.science20.com/taxonomy/term/7/2">Science 2.0 - Physical Sciences</a>  </li>
<li> <a href="http://www.guardian.co.uk/science/life-and-physics">Science: Life and Physics | guardian.co.uk</a>  </li>
<li> <a href="http://pipes.yahoo.com/pipes/pipe.info?_id=fKlwSynj3RGeI1v_PhJ3AQ">SciencePunk</a>  </li>
<li> <a href="http://www.skepticalscience.com/">Skeptical Science</a>  </li>
<li> <a href="http://science.slashdot.org/">Slashdot: Science</a>  </li>
<li> <a href="http://scienceblogs.com/startswithabang/">Starts With A Bang</a>  </li>
<li> <a href="http://www.symmetrymagazine.org/breaking">symmetry breaking</a>  </li>
<li> <a href="http://www.ted.com/talks/list">TEDTalks (video)</a>  </li>
<li> <a href="http://thebigblogtheory.wordpress.com">The Big Blog Theory</a>  </li>
<li> <a href="http://theenergycollective.com/rss">The Energy Collective</a>  </li>

<li> <a href="http://scienceblogs.com/scientificactivist/">The Scientific Activist</a>  </li>
<li> <a href="http://scienceblogs.com/principles/">Uncertain Principles</a>  </li>
<li> <a href="http://blogs.uslhc.us">US LHC Blog</a>  </li>
<li> <a href="http://blog.vixra.org">viXra log</a>  </li>
<li> <a href="http://www.wired.com/wiredscience">Wired Science</a>  </li>
<li> <a href="http://fatasmihov.blogspot.com/">MathStatEcon</a>  </li>
<li> <a href="http://datamining.typepad.com/data_mining/">Data Mining: Text Mining, Visualization and Social Media</a>  </li>
<li> <a href="http://datamining.typepad.com/data_mining/">Data Mining: Text Mining, Visualization and Social Media</a>  </li>
<li> <a href="http://datavisualization.ch">Datavisualization.ch</a>  </li>
<li> <a href="http://www.econbrowser.com/">Econbrowser</a>  </li>
<li> <a href="http://economistsview.typepad.com/economistsview/">Economist's View</a>  </li>
<li> <a href="http://economix.blogs.nytimes.com/">Economix</a>  </li>
<li> <a href="http://blogs.reuters.com/felix-salmon">Felix Salmon</a>  </li>
<li> <a href="http://fivethirtyeight.blogs.nytimes.com/">FiveThirtyEight</a>  </li>
<li> <a href="http://flowingdata.com">FlowingData</a>  </li>
<li> <a href="http://www.freakonomics.com">Freakonomics</a>  </li>
<li> <a href="http://www.freakonomics.com">Freakonomics</a>  </li>
<li> <a href="http://www.economist.com/blogs/freeexchange">Free exchange</a>  </li>
<li> <a href="http://scientopia.org/blogs/goodmath">Good Math, Bad Math</a>  </li>
<li> <a href="http://delong.typepad.com/sdj/">Grasping Reality with  a Sharp Beak</a>  </li>
<li> <a href="htton.wordpress.com">Gödel's Lost Letter and P=NP</a>  </li>
<li> <a href="http://infosthetics.com/">information aesthetics</a>  </li>
<li> <a href="http://junkcharts.typepad.com/junk_charts/">Junk Charts</a>  </li>
<li> <a href="http://www.nakedcapitalism.com">naked capitalism</a>  </li>
<li> <a href="http://www.npr.org/blogs/money/">NPR Blogs: Planet Money</a>  </li>
<li> <a href="http://junkcharts.typepad.com/numbersruleyourworld/">Numbers Rule Your World</a>  </li>
<li> <a href="http://paul.kedrosky.com">Paul Kedrosky's Infectious Greed</a>  </li>
<li> <a href="http://paul.kedrosky.com">Paul Kedrosky's Infectious Greed</a>  </li>
<li> <a href="htttp://math.columbia.edu/~dejong/wordpress">Stacks Project Blog</a>  </li>
<li> <a href="http://andrewgelman.com">Statistical Modeling, Causal Inference, and Social Science</a>  </li>
<li> <a href="http://blogs.wsj.com/numbersguy">The Numbers Guy</a>  </li>
<li> <a href="http://statisticsforum.wordpress.com">(title unknown)</a>  </li>
<li> <a href="http://terrytao.wordpress.com">What's new</a>  </li>
<li> <a href="http://terrytao.wordpress.com">What's new</a>  </li>
