

     
	 <img src="/images/feynman.jpeg" alt="" class="centercolumn" style="width:80%;" >

	 <div class="caption">
	 Richard Feynman, theoretical physicists, Nobel Laureate, and all around fascinating person.
	 </div>

	 <br>
     
	 <img src="/images/YoungEinstein.jpeg" alt="" class="centercolumn" style="width:80%;" >

	 <div class="caption">
	 A young Einstein around the time when he invented special relativity (a part of his <a href="http://en.wikipedia.org/wiki/Annus_Mirabilis_papers">annus mirabilis</a> in 1905).
	 </div>
